### ISSUE TITLE
Parallel builds in Codebuild

### ISSUE THREAD

**Issue by nadiiaparsons** [TheKevJames/coveralls-python#383]
I am trying to run parallel builds in one repo (AWS Codebuild) and upload joined coverage to Coveralls.
```
  build:
    commands:
  - poetry run coverage run -m pytest . 
  - COVERALLS_PARALLEL=true poetry run coveralls

 post_build:
    commands:
      - curl -k "https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN" -d "payload[build_num]=$CODEBUILD_BUILD_NUMBER&payload[status]=done"
```
When running command `curl -k "https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN" -d "payload[build_num]=$CODEBUILD_BUILD_NUMBER&payload[status]=done"`

I get an error {"error":"No build matching CI build number 19 found"}

How can I add parallel builds webhook for Codebuild?
